### ISSUE TITLE
Impossible to instantiate module `ttx.diacritics`

### ISSUE THREAD

**Issue by Grmiade** [Kepro/angular-remove-diacritics#2]
`bower install angular-remove-diacritics` don't return the last version.

**Comment by VanAxe** [comment]
+1

**Comment by VanAxe** [comment]
Bower will not fetch HEAD from a gihub repo unless forced. Creating a new tag and matching said tag in bower.json will resolve the issue.

Users needing to use this module right away can install with `bower install '<git-url>#<git-commit-sha>'` or in this case the latest commit at time of comment `bower install --save git://github.com/Kepro/angular-remove-diacritics.git#169751a9a7c9542713091bd0d9dadd1edf991363`. zsh users may want to escape that `#`.

Yarr.

**Comment by Kepro** [comment]
thanks! now i create new release
